#!/usr/bin/env bash
# Create `.env.staging` from the example with generated local secrets.
# Does NOT invent live AML/FX/Fiat vendor API keys — those must be pasted from vaults.
# Safe to re-run: never overwrites an existing `.env.staging`.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

OUT=".env.staging"
EXAMPLE=".env.staging.example"

if [[ -f "$OUT" ]]; then
  echo "$OUT already exists — leave unchanged"
  exit 0
fi
[[ -f "$EXAMPLE" ]] || { echo "missing $EXAMPLE" >&2; exit 1; }

PII_KEY=$(openssl rand -base64 32)
INTERNAL=$(openssl rand -hex 32)
EXPLORER=$(openssl rand -hex 32)
QUOTE_SECRET=$(openssl rand -hex 32)
WEBHOOK_TOKEN=$(openssl rand -hex 24)

cp "$EXAMPLE" "$OUT"
{
  echo ""
  echo "# ── Generated by scripts/smoke/prepare-staging-env.sh ($(date -u +%Y-%m-%dT%H:%MZ)) ──"
  echo "INTERNAL_SERVICE_TOKEN=$INTERNAL"
  echo "EXPLORER_READ_TOKEN=$EXPLORER"
  echo "COMPLIANCE_PII_ENC_KEY=$PII_KEY"
  echo "LIQUIDITY_QUOTE_SIGNING_SECRET=$QUOTE_SECRET"
  echo "EXECUTION_INTERNAL_WEBHOOK_TOKEN=$WEBHOOK_TOKEN"
} >>"$OUT"

echo "Created $OUT with generated tokens/keys."
echo "Still required before staging boot (paste from vendor dashboards):"
echo "  CHAINALYSIS_API_KEY / COMPLYADVANTAGE_API_KEY (or disable composite)"
echo "  FLUTTERWAVE_SECRET_KEY and/or PAYSTACK_SECRET_KEY"
echo "  KMS_AWS_KEY_ID (when KMS_PROVIDER=aws)"
echo "See docs/runbooks/staging-vendor-posture.md"
