import {
  Activity,
  ArrowDownToLine,
  ArrowLeftRight,
  Banknote,
  Bot,
  Brain,
  Building2,
  Cog,
  Compass,
  CreditCard,
  Database,
  FileCode2,
  Gauge,
  GraduationCap,
  HeartPulse,
  Landmark,
  Layers,
  LayoutDashboard,
  LineChart,
  Network,
  Package,
  Plane,
  Plug,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  TrendingUp,
  Users,
  Wallet,
  Wheat,
} from 'lucide-react';
import type { SidebarItem } from '@salychain/ui';

export const navItems: readonly SidebarItem[] = [
  { key: 'dashboard', label: 'Dashboard', href: '/', icon: LayoutDashboard },
  { key: 'overview', label: 'Overview', href: '/overview', icon: Compass },
  { key: 'analytics', label: 'Analytics', href: '/analytics', icon: LineChart },
  { key: 'transactions', label: 'Transactions', href: '/transactions', icon: ArrowLeftRight },
  { key: 'escrow', label: 'Escrow', href: '/escrow', icon: ShieldCheck },
  { key: 'payroll', label: 'Payroll', href: '/payroll', icon: Banknote },
  { key: 'clearing', label: 'Clearing', href: '/clearing', icon: ArrowDownToLine },
  { key: 'approvals', label: 'Spend Approvals', href: '/approvals', icon: ShieldCheck },
  { key: 'intents', label: 'Intents', href: '/intents', icon: Brain },
  { key: 'users', label: 'Users', href: '/users', icon: Users },
  { key: 'businesses', label: 'Businesses', href: '/businesses', icon: Building2 },
  { key: 'verticals', label: 'Verticals', href: '/verticals', icon: Layers },
  { key: 'verticals-finance', label: 'Finance', href: '/verticals/finance', icon: TrendingUp },
  { key: 'verticals-gov', label: 'Government', href: '/verticals/gov', icon: Landmark },
  { key: 'verticals-health', label: 'Healthcare', href: '/verticals/health', icon: HeartPulse },
  { key: 'verticals-agents', label: 'Agent Marketplace', href: '/verticals/agents', icon: Bot },
  { key: 'verticals-agri', label: 'Agriculture', href: '/verticals/agri', icon: Wheat },
  { key: 'verticals-scm', label: 'Supply chain', href: '/verticals/scm', icon: Package },
  { key: 'verticals-aviation', label: 'Aviation', href: '/verticals/aviation', icon: Plane },
  { key: 'verticals-edu', label: 'Education', href: '/verticals/edu', icon: GraduationCap },
  { key: 'developers', label: 'Developers', href: '/developers', icon: FileCode2 },
  { key: 'wallets', label: 'Wallets', href: '/wallets', icon: Wallet },
  { key: 'liquidity', label: 'Liquidity', href: '/liquidity', icon: Database },
  { key: 'routing', label: 'Routing', href: '/routing', icon: Network },
  { key: 'l3', label: 'L3 Rollup', href: '/l3', icon: Layers },
  { key: 'contracts', label: 'Smart Contracts', href: '/contracts', icon: FileCode2 },
  { key: 'compliance', label: 'KYC / Compliance', href: '/compliance', icon: ShieldCheck },
  { key: 'risk', label: 'Risk & Fraud', href: '/risk', icon: ShieldAlert },
  { key: 'ai', label: 'AI Insights', href: '/ai-insights', icon: Sparkles },
  { key: 'monitoring', label: 'System Monitoring', href: '/monitoring', icon: Gauge },
  { key: 'integrations', label: 'Integrations', href: '/integrations', icon: Plug },
  { key: 'settings', label: 'Settings', href: '/settings', icon: Cog },
];

export const iconForMetric = {
  volume: CreditCard,
  transactions: ArrowLeftRight,
  users: Users,
  wallets: Wallet,
  revenue: Activity,
};
