-- AlterEnum
ALTER TYPE "BroadcastJobKind" ADD VALUE IF NOT EXISTS 'BRIDGE_DEPOSIT';
ALTER TYPE "BroadcastJobKind" ADD VALUE IF NOT EXISTS 'BRIDGE_WITHDRAW';

ALTER TABLE "broadcast_jobs" ADD COLUMN IF NOT EXISTS "bridge_payload" JSONB;
