apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: salychain-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: salychain
  source:
    repoURL: https://github.com/salychain/salychain.git
    targetRevision: main
    path: infra/helm/salychain
    helm:
      releaseName: salychain
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: salychain-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
