apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-shared-env
  labels:
    {{- include "salychain.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.global.sharedEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
