{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "salychain.signerServiceAccountName" . }}
  labels:
    {{- include "salychain.labels" . | nindent 4 }}
    app.kubernetes.io/name: signer
  {{- with .Values.serviceAccount.signer }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
