-- This migration is applied after the initial schema migration generated by
-- `prisma migrate dev`. It installs the database-level safety net that
-- enforces double-entry balance per JournalEntry per currency. Application
-- code is the primary defense; this trigger is the last line.

CREATE OR REPLACE FUNCTION saly_check_journal_balance()
RETURNS TRIGGER AS $$
DECLARE
  v_unbalanced RECORD;
BEGIN
  -- Only validate when an entry transitions to POSTED.
  IF NEW.status <> 'POSTED' THEN
    RETURN NEW;
  END IF;

  -- Sum debits and credits per currency for this entry. They must net to zero.
  SELECT currency,
         SUM(CASE WHEN direction = 'DEBIT'  THEN amount_minor ELSE 0 END) AS debits,
         SUM(CASE WHEN direction = 'CREDIT' THEN amount_minor ELSE 0 END) AS credits
    INTO v_unbalanced
    FROM postings
   WHERE journal_entry_id = NEW.id
   GROUP BY currency
  HAVING SUM(CASE WHEN direction = 'DEBIT'  THEN amount_minor ELSE 0 END)
       <> SUM(CASE WHEN direction = 'CREDIT' THEN amount_minor ELSE 0 END);

  IF FOUND THEN
    RAISE EXCEPTION 'salychain_ledger.unbalanced_journal_entry: entry % currency % debits=% credits=%',
      NEW.id, v_unbalanced.currency, v_unbalanced.debits, v_unbalanced.credits
      USING ERRCODE = 'check_violation';
  END IF;

  -- At least one posting required.
  IF (SELECT COUNT(*) FROM postings WHERE journal_entry_id = NEW.id) = 0 THEN
    RAISE EXCEPTION 'salychain_ledger.empty_journal_entry: entry % has no postings', NEW.id
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_check_journal_balance ON journal_entries;
CREATE CONSTRAINT TRIGGER trg_check_journal_balance
  AFTER INSERT OR UPDATE OF status
  ON journal_entries
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW
  EXECUTE FUNCTION saly_check_journal_balance();

-- Postings are immutable after creation. Reversals are new entries, not edits.
CREATE OR REPLACE FUNCTION saly_postings_immutable()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'salychain_ledger.postings_are_immutable: postings cannot be updated or deleted'
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_postings_no_update ON postings;
CREATE TRIGGER trg_postings_no_update
  BEFORE UPDATE OR DELETE ON postings
  FOR EACH ROW
  EXECUTE FUNCTION saly_postings_immutable();
